/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAddShadowsToGltf } from "./useAddShadowsToGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/D20_draco.glb");
  useAddShadowsToGltf(group);

  return (
    <mesh
      ref={group}
      {...props}
      material={nodes.Mesh_0.material}
      geometry={nodes.Mesh_0.geometry}
      position={[0, 0, 0]}
    >
      {props.children}
    </mesh>
  );
}
useGLTF.preload("/models/D20_draco.glb");
